[project]
name = "anon-to-zenodo"
version = "0.1.0"
description = "Utility to zip a directory and upload to Zenodo with versioning"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "zenodo-client>=0.3.6",
]
